### ISSUE TITLE
Process watchdog thread crashes

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#174]
The process watchdog function, used by setting `process_watchdog=True` when initializing a TaskManager, crashes shortly after a crawl is started with the following stack:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File ".../OpenWPM/automation/TaskManager.py", line 230, in _manager_watchdog
    "supported." % self.crawl_id)
AttributeError: TaskManager instance has no attribute 'crawl_id'
```

**Comment by boolean5** [comment]
I think this issue can be closed now because commit d4f5c70 in https://github.com/mozilla/OpenWPM/pull/467 removed the line that caused this crash by mistakenly assuming that `crawl_id` was an attribute of `TaskManager`.
https://github.com/mozilla/OpenWPM/issues/598 has been opened to discuss what needs to be done to restore the functionality of the process watchdog.
