### ISSUE TITLE
Instrumentation updates needed to get tests working

### ISSUE THREAD

**Issue by nhnt11** [mozilla/OpenWPM#268]
Starting this issue as a place to document all the places in the tests where I've had to disable something or comment something out because something isn't supported in the new instrumentation yet.

We can use this issue for tracking and come back and tackle them 1 by 1 - whether they need to be implemented in the instrumentation or removed from the test, etc.

I'm going to be pasting the TODO comments here so they can easily be searched for in code.

**Comment by nhnt11** [comment]
test_http_instrumenation.py: TODO: webext instrumentation doesn't save the content_hash yet.

**Comment by nhnt11** [comment]
test_http_instrumenation.py: TODO: webext instrumentation doesn't support referrer yet

**Comment by nhnt11** [comment]
test_http_instrumentation.py: TODO: webext instrumentation doesn't support new_request_id yet

**Comment by nhnt11** [comment]
test_http_instrumentation.py: TODO: webext instrumentation doesn't support req_call_stack yet.

**Comment by englehardt** [comment]
` # TODO: Can we fix this in the extension?` in `S3Aggregator.py`. The same conversion happens in `LocalAggregator.py`, but is not marked with a TODO. The extension is sending back dictionary records. We should figure out if this is intentional, or whether we should be performing the serialization to json (or another format) within the extension.

**Comment by englehardt** [comment]
All of these are captured in https://github.com/mozilla/openwpm-webext-instrumentation/issues/17 with the exception of the S3Aggregator issue. I'm already planning to fix that as we add tests for the S3Aggregator.
