### ISSUE TITLE
content.js "could not establish connection" errors in the console

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#289]
See #288 for an example. `JavaScript error: moz-extension://6cbcf7fe-c654-4558-bfa1-bcc2f8a7769c/content.js, line 983: Error: Could not establish connection. Receiving end does not exist.`

Possible cause? https://stackoverflow.com/questions/44673632/firefox-webextension-error-could-not-establish-connection-receiving-end-does-n

**Comment by nhnt11** [comment]
This happens when the JS instrument is not enabled - we are injecting the instrumentation anyway but nothing is listening for the messages in the privileged scope.

The solution is to either only inject our instrumentation if the JS instrument is enabled in the config, or to silently ignore this error by wrapping the block in a try/catch. The problem with the former is that it will likely cause an async delay while injecting our script which will cripple its utility. The problem with the latter is that it will suppress legitimate errors.

**Comment by englehardt** [comment]
We should figure out how to do the former. The `content.js` script mucks with a lot of the JS APIs, so there may be crawls where we want it disabled (especially if we're not collecting JS data for those crawls).

**Comment by tooflop101** [comment]
I solved the problem # 288 by installing the repository 0.8 by downloading it from the link. Errors occurred when installing via the console of an unknown version through the command git clone.Version 0.8 is stable.

**Comment by motin** [comment]
This was fixed in #375 along with #374
