### ISSUE TITLE
Profile information lost during timeout

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#40]
Some profile information is lost during timeouts or crashes. By profile information I mean rows in `places.sqlite` and `cookies.sqlite`. The amount of data loss varies by the site, but can sometimes be all data from the site visit.

My suspicion is that this is the result of sqlite's [write-ahead logging](https://www.sqlite.org/wal.html). The temporary wal files that were written prior to the timeout or crash are never successfully synced with the main database after the profile are recovered and are instead discarded.

I haven't confirmed this as the cause, but if it is, it should be possible to connect to the databases directly and force the wal sync to occur before copying over the database.

**Comment by boolean5** [comment]
Having read SQLite's write-ahead log documentation, this is certainly not the expected behavior. Since we copy the `*-wal` files along with the main sqlite database files they should sync and we should not be losing any data, unless the db files are [corrupted](https://www.sqlite.org/howtocorrupt.html).

I tried to reproduce this issue in two ways, using [`test_browser_profile_coverage`](https://github.com/mozilla/OpenWPM/blob/8030c2c470015350f510af4e42f1389e1ffe1c1c/test/test_crawl.py#L46):  

1. By issuing a `killall -9 firefox-bin` command several times throughout the duration of the test, causing the browser to restart.

2. By setting a low timeout for some of the site visits, again causing browser restarts.

In both cases `test_browser_profile_coverage` was passing.

@englehardt, @vringar, this is a very old issue and a lot has changed since then, so unless we can come up with another way to reproduce this I'm thinking of closing it. What do you think?

**Comment by vringar** [comment]
I can't think of a way to provoke more drastic crashes.
Since your research shows that this is no longer an issue, I'm voting for closing this issue.

**Comment by englehardt** [comment]
> I can't think of a way to provoke more drastic crashes.
> Since your research shows that this is no longer an issue, I'm voting for closing this issue.

Agreed. This is as comprehensive as I'd expect. Thank you!
