### ISSUE TITLE
Make it possible to know whether or not a site visit lead to fully saved visit-related data

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#443]
In https://github.com/mozilla/openwpm-crawler/issues/23#issuecomment-518279520 we discussed this. 

By for instance saving a flag in crawl_history data_saved = True or making sure that the whole crawl_history record is only saved after all visit-related data is saved, we can be more confident in using that visit-related data in analysis. 

We can also employ a retry-strategy (such as https://github.com/mozilla/openwpm-crawler/issues/23) to incrementally increase the crawl success rate.

**Comment by englehardt** [comment]
Thinking a bit more about my comment in https://github.com/mozilla/openwpm-crawler/issues/23#issuecomment-518279520, I think it's likely that all data for a process has been written when the `crawl_history` record is included in the database. This record is [sent to the DataAggregator](https://github.com/mozilla/OpenWPM/blob/e9c1baa0582a6ede58e0230d5c947952cbf607a6/automation/TaskManager.py#L464-L470) at the end of a page visit. Note that this is before the manager process moves the worker process to the next site, so it's possible the worker is still sending some data after this record is sent, but it will be for a small window of time at the tail end of the page visit. The `crawl_history` record will be queued for upload along with the rest of the data for that `visit_id` and will be sent to S3 with the rest of the batch.

The only way the `crawl_history` record will be present, but data lost is if the `S3Aggregator` doesn't receive any new data for a time close to the [commit timeout](https://github.com/mozilla/OpenWPM/blob/e9c1baa0582a6ede58e0230d5c947952cbf607a6/automation/DataAggregator/S3Aggregator.py#L222-L237) -- currently 30 seconds. Then hits the timeout while the `crawl_history` record from the manager process is added to the aggregator's queue (thus being included in the batch committed due to timeout), and then starts receiving data again from the worker process before the manager has time to kill it, and then crashes / is killed before the next commit (i.e., the start of the next page visit for that worker).  

@motin To answer your question in https://github.com/mozilla/openwpm-crawler/issues/23#issuecomment-518578646:

>The current implementation does some differentiation based on command success (1), command failure (0) and command timeout (-1) but I am not sure what this translates to. @englehardt can you shine a light on this?

These are set based on the status of the process executing the page visit. Basically the manager process sends a command to a worker and then checks a status queue for the result. [This code](https://github.com/mozilla/OpenWPM/blob/e9c1baa0582a6ede58e0230d5c947952cbf607a6/automation/TaskManager.py#L437-L462) shows how those three conditions are set, and [this code](https://github.com/mozilla/OpenWPM/blob/e9c1baa0582a6ede58e0230d5c947952cbf607a6/automation/BrowserManager.py#L397-L414) shows how the browser process generates these conditions.

@birdsarah Following up on your comment https://github.com/mozilla/openwpm-crawler/issues/23#issuecomment-518318409

> I am generally in support of this, but for some things it feels like a workaround for issues that are just bugs within openwpm. e.g. losing hundreds of sites worth of successfully collected data because of how we've chosen to batch data.

I agree. Do you have a sense for how long it would take to re-partition a dataset that has one parquet file per visit (thus ending up with 1 million tiny parquet files in each table at the end of a 1-million-site crawl)? Before I implemented batching I was writing one file per site and the load times were super high (I can't remember exact times though). It's only a one-time cost though, so it's totally fine if it takes a few hours to process the raw data after a crawl. This is the simplest solution. We could simply implement [lease expiration](https://github.com/mozilla/OpenWPM/blob/e9c1baa0582a6ede58e0230d5c947952cbf607a6/automation/utilities/rediswq.py#L61-L78) and define a retry strategy to re-crawl the sites that fail.

If we aren't comfortable writing data out for each site, we could instead implement a smaller batch, distribute batches of sites (instead of individual sites), and then retry the entire batch if there's a failure. We'd still need lease expiration but we could do it by batch rather than site, and only mark a batch complete after the entire batch is uploaded.

**Comment by vringar** [comment]
I think this #574 fixes this issue for the most part.
We could however discuss if we should mark visits that were cut short by a shutdown as such in some table.

**Comment by birdsarah** [comment]
> We could however discuss if we should mark visits that were cut short by a shutdown as such in some table.

Visits cut short by a shutdown should definitely be marked as failed. In an ideal world their data wouldn't be saved.

The only reason that it's probably not urgent is that it doesn't happen very often but it definitely invalidates the measurement if it didn't get a chance to complete for the requested time.

**Comment by vringar** [comment]
We definitely will save their data online but we could easily implement a post processing step that removes all rows of failed crawls for the analysis and keep the sites marked as not done in the work_queue
