### ISSUE TITLE
Investigate why the MPLogger tests failed to capture serialization issues

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#534]
See https://github.com/mozilla/OpenWPM/pull/532#discussion_r349558424 for a discussion of the bug, and https://github.com/mozilla/OpenWPM/issues/487 for an example of how the bug manifests.

**Comment by englehardt** [comment]
#532 should fix #487, but lets leave it open until we're able to get a working test case.

**Comment by vringar** [comment]
The exception difference between the testcases and the error we are seeing in #532 is that the WebDriverException in a real run gets caught in the BrowserManager, has it's exception formatted and then logged and put into the status queue. [See here for the code](https://github.com/mozilla/OpenWPM/blob/master/automation/BrowserManager.py#L485)

**Comment by vringar** [comment]
What I currently don't understand how the status queue in the browser manager relates to the one in BrowserManager or if it's the `exc_info=True, extra = extra` that is causing this behaviour as both don't appear in the test cases
 ```Python
logger.error(
                    "BROWSER %i: WebDriverException while executing command" %
                    browser_params['crawl_id'], exc_info=True, extra=extra
                )
```

**Comment by vringar** [comment]
Somehow having `Process` in `multiprocess_utils.py` name the exception causes it to be saved in `exc_text` instead of `exc_info`. [According to the docs](https://docs.python.org/3/library/logging.html#logging.Formatter.format) this is a field where a preformatted string can be cached.
Because of this caching the test case never hit the `ensure_string` code path.
