### ISSUE TITLE
UnboundLocalError: local variable 'command_status' referenced before assignment

### ISSUE THREAD

**Issue by turban1988** [mozilla/OpenWPM#546]
When I perfom large-sacle  crawls i often get the following error (undeterministically).

```
Exception in thread Thread-1209:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<path>/OpenWPM/automation/TaskManager.py", line 512, in _issue_command
    "command_status": command_status,
UnboundLocalError: local variable 'command_status' referenced before assignment
```

The relate dcode is:
https://github.com/mozilla/OpenWPM/blob/8ed3798c45ce01729458a794748fe018a81727e2/automation/TaskManager.py#L461-L515

It seams that if an eception (other than `EmptyQueue`) is raised the `command_status` is never set. A work around might be to initialize it before teh if statement or within the final `else`. But both seems to be quick and dirty as teh problem is probably somewhere else.

**Comment by englehardt** [comment]
> It seams that if an eception (other than EmptyQueue) is raised the command_status is never set.

That doesn't seem right, because we'd never get to line 512 if an unhandled exception were thrown.  The same goes for the [`else` condition](https://github.com/mozilla/OpenWPM/blob/8ed3798c45ce01729458a794748fe018a81727e2/automation/TaskManager.py#L496-L499) which would throw a `ValueError`.

Instead, it looks like this will happen if there is a critical command failure, since we don't set `command_status` in the `elif status[0] == "CRITICAL": ` condition. There are two possible fixes here:

https://github.com/mozilla/OpenWPM/blob/12b23cc2c490033d8e6e9c7381e3a4432b3ae361/automation/TaskManager.py#L504-L519

move the `if critical_failure:` above the `sock.send` command, or actually set `command_status = 'critical'` within the `elif status[0] == "CRITICAL": ` condition. The latter seems preferable, so we'd at least log that there's a critical failure (assuming the failure wasn't caused by the data aggregator process crashing).
