### ISSUE TITLE
Scanning site with the containerised version

### ISSUE THREAD

**Issue by CuttlefishJones** [mozilla/OpenWPM#558]
I've been handed the containerised version of OpenWPM to perform cookie audits of sites but I can't see how you pass your own configuration to the container. I've tried mapping an external dir to /opt/OpenWPM but that just fails with No module named 'automation'. Any help would be appreciated.

**Comment by vringar** [comment]
Hey,
Can you go into more detail on what kind of configuration you would like to do?

My general suggestion would be to either:
1. Use our image as a base image, add your script into the /opt/OpenWPM directory (as that is where our code lives) and then run your python script.
2. Mount your script someplace else into the container and then add /opt/OpenWPM to your python path, so that the automation module gets found
