### ISSUE TITLE
Set site_rank in crawler.py

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#564]
Since we now have the ability to save site rank in the DB we should set it in crawler.py

**Comment by svensevenslow** [comment]
Hi! I'm a Outreachy 2020 participant. I'd like to work on this issue. Could you please assign it to me?

**Comment by svensevenslow** [comment]
Hi! I'm not clear on what it means here to set the site_rank. The crawler.py file has this line of code
[site_rank, site = job.decode("utf-8").split(',')](https://github.com/mozilla/OpenWPM/blob/59e79a7adbb41b2a801b7f8fb9c2863cb6222cc7/crawler.py#L124)

**Comment by vringar** [comment]
Hey,
Oh that's convenient. So passing this to [the command sequence constructor](https://github.com/mozilla/OpenWPM/blob/master/automation/CommandSequence.py#L25) [five lines below](https://github.com/mozilla/OpenWPM/blob/59e79a7adbb41b2a801b7f8fb9c2863cb6222cc7/crawler.py#L129) should fix this bug.
Because right now `site_rank` seems to be unused.

**Comment by svensevenslow** [comment]
Hi! I've opened a [PR](https://github.com/mozilla/OpenWPM/pull/575).

**Comment by vringar** [comment]
Hey, thank you so much!
Are you aware that you can get GitHub to automatically close the issue you are fixing by writing

>  Closes #564

in the description of the merge request?

**Comment by svensevenslow** [comment]
Hi! Didn't know, will keep it in mind next time. Thank you for merging my PR.
