### ISSUE TITLE
Collect SRI info of scripts

### ISSUE THREAD

**Issue by turban1988** [mozilla/OpenWPM#573]
Hi,

it would be great if information on Subresource Integrity (SRI) could be collected during the crawl.
Would that be possible?

**Comment by vringar** [comment]
Hey, you could write a custom function as [seen here](https://github.com/mozilla/OpenWPM/issues/570) and access any information available on the site

**Comment by englehardt** [comment]
@vringar is right. This seems more appropriate as a Selenium command than something built into the native instrumentation.

I don't see a way to collect SRI information using the probes we currently have in place. I'm hesitant to add commands that parse page content since there's a lot of subjectivity involved in that (e.g., when to start parsing, do we go into iframes, etc). It seems safer to allow the user to write that code.
