### ISSUE TITLE
Running install.sh in a virtual environment fails

### ISSUE THREAD

**Issue by boolean5** [mozilla/OpenWPM#577]
The installation instructions in the README suggest running `install.sh` in a virtual environment, but the `--user` flag is used in `install-pip-and-packages.sh` (specifically in the commands `python3 get-pip.py --user` and `pip3 install --user --upgrade -r requirements.txt`).

This results in `install.sh` failing with `ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`

Removing the `--user` flag seems to work. What was the rationale behind using this flag in this case? Is it necessary?

**Comment by vringar** [comment]
AFAIK the `--user` flag installs packages into the user directory to avoid requiring root access and still make the packages available for all local projects.
Since we suggest using a virtualenv to keep the installed packages (with their fixed versions) contained to the project.
Unless I'm missing something I would think that we can remove the `--user` flag
@englehardt @skim1102

**Comment by englehardt** [comment]
> AFAIK the `--user` flag installs packages into the user directory to avoid requiring root access and still make the packages available for all local projects.
> Since we suggest using a virtualenv to keep the installed packages (with their fixed versions) contained to the project.
> Unless I'm missing something I would think that we can remove the `--user` flag
> @englehardt @skim1102

That sounds right. I believe we added this avoid using `sudo` to work around permission errors when not using a virtualenv (e.g., deploying crawls to a cloud machine).

Given that pip now [falls back](https://github.com/pypa/pip/pull/7002) to `--user` under those conditions, removing the explicit `--user` flag from the install script seems right.
