### ISSUE TITLE
Use extension cookie instrumentation as the default cookie instrumentation

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#76]
Right now the default cookie instrumentation is via the proxy, where `Set-Cookie` and `Cookie` headers are parsed from HTTP responses and requests, respectively.

While this works quite well, any cookies set by javascript (i.e. set using `document.cookie`) will not be recorded alongside cookies set with a `Set-Cookie` header. The cookies will still be seen alongside requests in `Cookie` headers, but we won't know any of the actual cookie attributes (e.g. `domain`, `expiry`, `secure`, etc).

Necessary steps:
1. Change the javascript cookies scheme to match the HTTP cookies schema, making the transition easier for current analysis scripts.
2. Write tests to confirm javascript cookie instrumentation works as expected.
3. Compare HTTP cookies to javascript extension cookies, checking for discrepancies.

**Comment by gunesacar** [comment]
https://github.com/citp/OpenWPM/pull/127 added instrumentation for cookies set by JavaScript.
https://github.com/citp/OpenWPM/issues/107 made the extension HTTP instrumentation the default.

There are tests for JavaScript cookies but can't find any tests on HTTP cookie instrumentation.

> Change the javascript cookies scheme to match the HTTP cookies schema, making the transition easier for current analysis scripts.

I wonder if this is still desirable or not.

Otherwise this issue could be closed, I guess.

**Comment by englehardt** [comment]
I'd like to have some tests for the cookie instrument and ideally compare the cookies observed with the HTTP instrumentation as a sanity check.

**Comment by englehardt** [comment]
Tests added in https://github.com/mozilla/OpenWPM/pull/318.
