### ISSUE TITLE
OpenWPM Watchdog Error

### ISSUE THREAD

**Issue by ankushduacodes** [mozilla/OpenWPM#778]
When ever I try to run demo.py, openwpm-watchdog gives the following error:
```Exception in thread OpenWPM-watchdog:
Traceback (most recent call last):
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/site-packages/psutil/_psosx.py", line 484, in memory_full_info
    uss = cext.proc_memory_uss(self.pid)
PermissionError: [Errno 13] Access denied (originated from task_for_pid)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ankushdua/Documents/GitHub/OpenWPM/automation/TaskManager.py", line 240, in _manager_watchdog
    mem_bytes += child.memory_full_info().uss
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 1094, in memory_full_info
    return self._proc.memory_full_info()
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/site-packages/psutil/_psosx.py", line 349, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=15450)
```

Operating System - MacOS 10.15.7

**Comment by vringar** [comment]
@ankushduacodes Do you want to stab at fixing this?

**Comment by ankushduacodes** [comment]
@vringar yes!... Thank you for mentioning me here, Can you please give me some head start as to what to look for in this issue?

**Comment by vringar** [comment]
Sure, I'll give you some basics now and if you have further questions I can answer them tomorrow (aka in 15h).
So in OpenWPM we have a so called watchdog in reference to [watchdog timers](https://en.wikipedia.org/wiki/Watchdog_timer) that tries to ensure two things.
1. That we don't forget to kill any GeckoDriver (or Xvfb) instances (GeckoDriver is used by Selenium to control Firefox and Xvfb a "virtual display" so we simulate having graphics when running on a server)
2. That no Firefox instance takes up to much memory

The first thing is called the `process_watchdog` and you can control it via the `manager_params`
The second thing is sometimes called `memory_watchdog` and currently you can't turn it off.

Some time ago another contributor [updated the memory_watchdog because it was outdated and unuseable](https://github.com/mozilla/OpenWPM/pull/596). After some discussion [they outlined a couple of solutions](https://github.com/mozilla/OpenWPM/pull/596#issuecomment-608728488). As you can read there all of the good solutions only work on Linux or have this note of
> requir[ing] higher user privileges than memory_info()

Apparently the new MacOS release locks down permissions to the point, where it always fails.

My suggestion would be, implement a new field in `manager_params` called `memory_watchdog` and set it to `false` by default.
Use this to check whether or not the `memory_watchdog` part of the code should run.

Imho the memory_watchdog is mostly useful for long running cloud crawls, so it's okay to be disabled by default. Pinging @englehardt  to get a second opinion on this.

Here is the code for the watchdog. Have a look at how `self.process_watchdog` is passed through the code, to see what other places you need to modify.
Also please copy what I wrote about the watchdog and add it to the documentation under docs/Platform-Architecture.md 
https://github.com/mozilla/OpenWPM/blob/93ddf80c185de5f4298a2870eb04b05a0bc522e8/automation/TaskManager.py#L214-L281

**Comment by ankushduacodes** [comment]
@vringar I have will be busy for the next couple of days as I have a college project to complete. I will start looking into this issue after I am done with my project and will ask further questions. I hope it's fine with you.

**Comment by englehardt** [comment]
> Imho the memory_watchdog is mostly useful for long running cloud crawls, so it's okay to be disabled by default. Pinging @englehardt to get a second opinion on this.

I agree. Specifically for long-running stateful crawls.

**Comment by vringar** [comment]
@ankushduacodes Please take all the time you need! I really appreciate you wanting to work on this at all and there is no rush to get this completed.

**Comment by ankushduacodes** [comment]
@vringar I have read through the provided resources, I have a few questions regarding the issue:
1. Higher level privileges are required to run memory_full_info(), Do you want me to write a check to see what platform the crawl is running on? if crawl if running on mac os then we set the memory_watchdog param to false else we keep it true.?. I know you are suggesting that memory_watchdog param be false by default but doesn’t this makes more sense?

2. Just to make sure I am getting it correctly, This code snippet below will be running under the condition 
`if self.memory_watchdog` right?
https://github.com/mozilla/OpenWPM/blob/93ddf80c185de5f4298a2870eb04b05a0bc522e8/automation/TaskManager.py#L226-L250

3. process_watchdog is only being used in Taskmanager.py so I am not really sure what you mean by the comment below:
> Here is the code for the watchdog. Have a look at how `self.process_watchdog` is passed through the code, to see what other places you need to modify.
https://github.com/mozilla/OpenWPM/blob/93ddf80c185de5f4298a2870eb04b05a0bc522e8/automation/TaskManager.py#L214-L281

4. Do you want to make memory_watchdog as a TaskManager class parameter just like process_watchdog or a browser_param(just making sure). If you want it to be a browser_param, then could you please confirm that browser_params are being loaded from default_browser_params.json file?

Thank You

**Comment by vringar** [comment]
Welcome back, I hope your project went well.
1. I don't think the memory watchdog should run by default since it doesn't add any meaningful value when not running in a cloud environment
2. Yes :)
3. Sorry for being imprecise, I mostly meant figuring out how `self.process_watchdog` gets set.
4. Thanks for pointing this out. I forgot that `process_watchdog` isn't in `manager_params`.
I think `process_watchdog` and `memory_watchdog` should be part of the **`manager`**`_params` with are stored in [default_manager_params.json](https://github.com/mozilla/OpenWPM/blob/master/automation/default_manager_params.json)
5. A long time ago instead of having a set of Geckodriver and xvfb pids to check we had the actual pids of the Firefox instances that were running. Maybe rename this to
```python
self.logger.debug( 
     "Process %s (pid: %i) with start " 
     "time %s isn't controlled by any BrowserManager."
     "Killing it now."
     % (process.name(), process.pid, process.create_time()) 
 ) 
```
or something similiar.

**Comment by ankushduacodes** [comment]
@vringar Is there a reason why docs/<filename>.md did not get forked?

**Comment by vringar** [comment]
Maybe your master branch is outdated. The .md files only landed there relatively recently. My suggestion would be to get your master branch up to date and then rebase your fix_mem_watchdog branch onto the new master.

**Comment by ankushduacodes** [comment]
I had rebased forked master branch with OpenWPM master branch before working on this issue

**Comment by ankushduacodes** [comment]
> Also please copy what I wrote about the watchdog and add it to the documentation under docs/Platform-Architecture.md

@vringar Do you want me to add this as h2 tag under TaskManager in docs/Platform-Architecture.md?

**Comment by vringar** [comment]
> I had rebased forked master branch with OpenWPM master branch before working on this issue

I moved the wiki into the repo in https://github.com/mozilla/OpenWPM/commit/e989ce5f74c1737185c89a33bde4015b55df066a so maybe check if that commit appears in your git log

**Comment by ankushduacodes** [comment]
> I had rebased forked master branch with OpenWPM master branch before working on this issue

@vringar This is available now sorry for any confusion
