### ISSUE TITLE
Generate Module index

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#895]
Somehow we aren't generating the module index right now.
This needs to be fixed ASAP

**Comment by boolean5** [comment]
It seems that for the module index to be created we have to run `sphinx-apidoc -o source/ ../openwpm` (from within the `docs` directory) and then commit the autogenerated `rst` files ([[1]](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/build-the-docs.html#generating-documentation-from-docstrings), [[2]](https://samnicholls.net/2016/06/15/how-to-sphinx-readthedocs/)).

This however, has the obvious drawback that we should remember to regenerate and commit these files whenever the structure of modules in our project changes, otherwise the documentation will be out of date. We could add a note about that in `CONTRIBUTING.md`, but it might be better if we could have readthedocs automatically run `sphinx-apidoc` before every build.

After looking into it a bit more, I came across this workaround, which does exactly that: https://github.com/readthedocs/readthedocs.org/issues/1139#issuecomment-312626491 

@vringar, I could open a PR if you haven't started working on something already.

**Comment by vringar** [comment]
Thanks for doing this investigation

I haven't started working on this yet so I'd appreciate a PR
